server:
  port: 8080
spring:
  application:
    name: Hello-AI
  ai:
    dashscope:
      api-key: sk-aadfa86963b247139112a71b02acdc72
      model: qwen-turbo

    mcp:
      client:
        enabled: true
        name: mcp-client
        version: 1.0.0
        type: SYNC
        request-timeout: 60000
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json
